--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.18
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
-- The following line is auto generated by pg_dump and there is no option to disable it. Clearing search_path globally
-- will cause the sql queries in our implementation fail (relation not found). So comment it out.
-- SELECT pg_catalog.set_config('search_path', '', false, 0);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: record_file; Type: TABLE DATA; Schema: public; Owner: mirror_node
--
INSERT INTO public.record_file (name, load_start, load_end, hash, prev_hash, consensus_start, consensus_end, node_account_id, count, digest_algorithm, hapi_version_major, hapi_version_minor, hapi_version_patch, version, file_hash, bytes, index) VALUES ('2021-03-06T22_31_10.319484000Z.rcd', 1615069874, 1615069874, '0e23db92250641deb65d2c6a18c18e693e61e3d9ba6d1336f018041a6c5a4b501a57de651743192fc2e2f8dfc657faec', '50f5a38fb8e0c0e80efbdf2f2f364c801f754c80673d7b13a205aebfe4f08c72a27b4d0b7bc53ce7f22ab0614a2ffad5', 1615069870319484000, 1615069871961936000, 3, 11, 0, 0, 11, 0, 5, '301a9ee0bd248c33e1bdb207c2b4b78ab3b273286ef65ea2e3994785a93698d997a503f7b99ea69bb4f2ad0b4246dfa9', NULL, 5397026);
