--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.18
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
-- The following line is auto generated by pg_dump and there is no option to disable it. Clearing search_path globally
-- will cause the sql queries in our implementation fail (relation not found). So comment it out.
-- SELECT pg_catalog.set_config('search_path', '', false, 0);

--
-- Data for Name: record_file; Type: TABLE DATA; Schema: public; Owner: mirror_node
--
INSERT INTO public.record_file (name, load_start, load_end, hash, prev_hash, consensus_start, consensus_end, node_account_id, count, digest_algorithm, hapi_version_major, hapi_version_minor, hapi_version_patch, version, file_hash, bytes, "index") VALUES
('2021-03-05T05_23_02.071338000Z.rcd', 1614921786, 1614921786, '366fee025a8b2b2678096cf7c1becdfe6e6a3ec2b904ff054a4a4f010e8136dce8bbe4b0c63e4807a2e8d0570f479f89', '9a59d0ea06adb84c8b5df9b118c16ce54a6986c326fd2b49c22fdee1de0550c2cbab1c25a001d6f14cb51619a224012b', 1614921782071338000, 1614921783306481000, 3, 7, 0, 0, 11, 0, 5, '6c16bb135f0237d9e340ecc1b87453bf2505f63aa4e4fdbcb343faa426f5ec63726250309f59dac3980b1272b39238fc', NULL, 4084);
