--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.18
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
-- The following line is auto generated by pg_dump and there is no option to disable it. Clearing search_path globally
-- will cause the sql queries in our implementation fail (relation not found). So comment it out.
-- SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: mirror_node
--

INSERT INTO public.transaction (consensus_timestamp, type, result, payer_account_id, valid_start_ns, valid_duration_seconds, node_account_id, entity_id, initial_balance, max_fee, charged_tx_fee, memo, transaction_hash, transaction_bytes, scheduled, nonce, parent_consensus_timestamp, errata, index) VALUES
  (1658802996804825645, 14, 22, 90, 1658802986066631632, 120, 3, NULL, 0, 100000000, 83989, '\x', '\x382ca706b3fbe5b2d3176237e131bb78940482078ab778d603ecaae6593c8b7543222aedc42aa47a8bac71e99be7cc60', NULL, false, 0, NULL, NULL, 0),
  (1658802996916571003, 14, 22, 90, 1658802983944059746, 120, 3, NULL, 0, 100000000, 83989, '\x', '\x86ae6344f88810f47de3d70f58fd47049fb9838fd09491619926b0e9e4e5c0b7eb977438d697abcceeb3eac45b515b5f', NULL, false, 0, NULL, NULL, 1),
  (1658802996916572003, 27, 22, 90, 1658802987519128529, 120, 3, 97228, 0, 200000000, 133915, '\x', '\x8bfec0eddda60e60dd773508d45d6fe722feb22898af47cc0d563b8c74b1542496023c13f77e3bde9e1ab0ae08d2954d', NULL, false, 0, NULL, NULL, 2),
  (1658802997657865003, 27, 22, 90, 1658802988720517604, 120, 3, 94299, 0, 1000000, 88715, '\x31363538383032393937353436204d6f6e69746f722070696e676572206f6e206d6972726f722d6d6f6e69746f722d363838363736663862662d706b6b3935', '\x2072082861bca09f24a53a85b57958f763ae8fcfc06b96877191cc6087269adc2055b458ee31d97d86bfde2fc1b71aea', NULL, false, 0, NULL, NULL, 3),
  (1658802997657866003, 14, 22, 90, 1658802985083931110, 120, 3, NULL, 0, 100000000, 83989, '\x', '\x9815561cfaebf310317c54673556a80954941863672108e443ce1d5162b3ca1b2293c3a9c07298443b07b4d0d095f665', NULL, false, 0, NULL, NULL, 4),
  (1658802997831841112, 14, 22, 90, 1658802987149094213, 120, 3, NULL, 0, 100000000, 83989, '\x', '\xd01b817507d63a66ce87905c0c80b7a6635e41970abcc5520e6d66e644565d865607bd40e77427807d68a6e36acac02f', NULL, false, 0, NULL, NULL, 5),
  (1658802997993304187, 14, 22, 90, 1658802985664035931, 120, 3, NULL, 0, 100000000, 83989, '\x', '\x9fe561bbf737d2e72d9fa85fb82de2725ca34a46244a2ff1aa5e31d2fadd7adc12e0d6837704d4c7e4b9fa0e3e98c32b', NULL, false, 0, NULL, NULL, 6),
  (1658802997993309003, 27, 22, 90, 1658802987014924223, 120, 3, 97228, 0, 200000000, 133915, '\x', '\x6932e05aa23f45a7287b848fc3f47f64baf807db6be3cbbfb67f1c43b23e98332400e6b8c7f8e0d6f8e4f8aa9f898e09', NULL, false, 0, NULL, NULL, 7);


--
-- PostgreSQL database dump complete
--
