package com.hedera.balanceFileLogger;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.hedera.configLoader.ConfigLoader;
import com.hedera.databaseUtilities.DatabaseUtilities;
import com.hedera.recordFileLogger.Entities;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.MarkerManager;


/**
 * This is a utility file to read back service record file generated by Hedera node
 */
public class BalanceFileHistoryLogger {

	private static final Logger log = LogManager.getLogger("recordStream-log");
	private static final Marker MARKER = MarkerManager.getMarker("SERVICE_RECORD");
	static final Marker LOGM_EXCEPTION = MarkerManager.getMarker("EXCEPTION");

    private static Connection connect = null;
    private static ConfigLoader configLoader = new ConfigLoader("./config/config.json");

    enum balance_history_fields {
        ZERO
        ,SNAPSHOT_TIME
        ,SECONDS
        ,FK_BAL_ID
        ,BALANCE 
    }

    enum balance_fields {
        ZERO
        ,SHARD
        ,REALM
        ,NUM 
    }

	enum select {
		ZERO
		,SHARD
		,REALM
		,NUM
	}

    static void moveFileToParsedDir(String fileName) {
		File sourceFile = new File(fileName);
		File parsedDir = new File(sourceFile.getParentFile().getParentFile().getPath() + "/parsedRecordFiles/");
		parsedDir.mkdirs();
		File destFile = new File(parsedDir.getPath() + "/" + sourceFile.getName());
		try {
			Files.move(sourceFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
			log.info(MARKER, sourceFile.toPath() + " has been moved to " + destFile.getPath());
		} catch (IOException ex) {
			log.error(MARKER, "Fail to move {} to {} : {}",
					fileName, parsedDir.getName(),
					ex.getStackTrace());
		}
	}
	
	public static boolean processFile(File balanceFile) {
        boolean processLine = false;
        boolean getDate = false;
        Entities entities;
        
        try {
            // process the file
            connect = DatabaseUtilities.openDatabase(connect);
            
            if (connect != null) {

                try {
        			connect.setAutoCommit(false);
        		} catch (SQLException e) {
                    log.error(LOGM_EXCEPTION, "Unable to unset database auto commit, Exception: {}", e.getMessage());
                	return false;
        		}
                
                PreparedStatement selectBalance = connect.prepareStatement(
                		"SELECT id"
                		+ " FROM t_account_balances"
                		+ " WHERE shard = ?"
                		+ " AND realm = ?"
                		+ " AND num = ?");
                
                PreparedStatement insertBalance = connect.prepareStatement(
                        "INSERT INTO t_account_balances (shard, realm, num, balance) "
                        + " VALUES (?, ?, ?, 0) "
                        + " RETURNING id");

            	PreparedStatement insertBalanceHistory;
	            insertBalanceHistory = connect.prepareStatement(
	                    "insert into t_account_balance_history (snapshot_time, seconds, fk_balance_id, balance) "
	                    + " values ("
	                    + " to_timestamp(?, 'YYYY,MONTH,DD,hh24,mi,ss')" // snapshot
	                    + ", EXTRACT(EPOCH FROM to_timestamp(?, 'YYYY,MONTH,DD,hh24,mi,ss'))" //seconds
	                    + ", ?" // balance_id
	                    + ", ?" // balance
	                    + ")"
	                    + " ON CONFLICT (snapshot_time, seconds, fk_balance_id)"
	                    + " DO UPDATE set balance = EXCLUDED.balance");
	        
	            BufferedReader br = new BufferedReader(new FileReader(balanceFile));
	
	            String line;
	            String dateLine = "";
	            while ((line = br.readLine()) != null) {
	                if (processLine) {
	                    try {
	                        String[] balanceLine = line.split(",");
	                        if (balanceLine.length != 4) {
		                        log.error(LOGM_EXCEPTION, "Balance file {} appears truncated", balanceFile);
		                        connect.rollback();
		                        insertBalanceHistory.close();
		                        selectBalance.close();
		                        insertBalance.close();
		                        br.close();
		                        return false;
	                        } else {
	                        	
	                        	// get the account id from t_Account_balances
	                        	long accountId = 0;
	                        	
	                        	selectBalance.setLong(select.SHARD.ordinal(), Long.valueOf(balanceLine[0]));
	                        	selectBalance.setLong(select.REALM.ordinal(), Long.valueOf(balanceLine[1]));
	                        	selectBalance.setLong(select.NUM.ordinal(), Long.valueOf(balanceLine[2]));
	                        	
	                        	selectBalance.execute();
	                        	ResultSet balanceRow = selectBalance.getResultSet();
	                        	
	                        	if (balanceRow.next()) {
	                        		accountId = balanceRow.getLong(1);
	                        	} else {
	                        		insertBalance.setLong(balance_fields.SHARD.ordinal(), Long.valueOf(balanceLine[0]));
	                        		insertBalance.setLong(balance_fields.REALM.ordinal(), Long.valueOf(balanceLine[1]));
	                        		insertBalance.setLong(balance_fields.NUM.ordinal(), Long.valueOf(balanceLine[2]));
	                        	
		                        	insertBalance.execute();

		                        	ResultSet newId = insertBalance.getResultSet();
		                            if (newId.next()) {
		                            	accountId = newId.getLong(1);
		                                newId.close();
		                            } else {
		                            	// failed to create or fetch the account from t_account_balances
		                                newId.close();
			                        	balanceRow.close();
		                            	throw new IllegalStateException("Unable to create or find, shard " + balanceLine[0] + ", realm " + balanceLine[1] + ", num " + balanceLine[2]);
		                            }
	                        	}
	                        	balanceRow.close();
	                        	
		                        insertBalanceHistory.setString(balance_history_fields.SNAPSHOT_TIME.ordinal(), dateLine);
		                        insertBalanceHistory.setString(balance_history_fields.SECONDS.ordinal(), dateLine);
	                        	insertBalanceHistory.setLong(balance_history_fields.FK_BAL_ID.ordinal(), accountId);
		                        insertBalanceHistory.setLong(balance_history_fields.BALANCE.ordinal(), Long.valueOf(balanceLine[3]));
		
		                        insertBalanceHistory.execute();
	                        }	                        
	                    } catch (SQLException e) {
	                        log.error(LOGM_EXCEPTION, "Exception {}", e);
	                        connect.rollback();
	                        insertBalanceHistory.close();
	                        selectBalance.close();
	                        insertBalance.close();
	                        br.close();
	                        return false;
	                    }
	                } else if (getDate) {
	                    getDate = false;
	                    dateLine = line;
	                } else if (line.contentEquals("year,month,day,hour,minute,second")) {
	                    getDate = true;
	                } else if (line.contentEquals("shard,realm,number,balance")) {
	                    // skip all lines until shard,realm,number,balance
	                    processLine = true;
	                }
	            }
	            connect.commit();
	            insertBalanceHistory.close();
                selectBalance.close();
            	insertBalance.close();
	            br.close();
	            return true;
            }
        } catch (FileNotFoundException e) {
            log.error(LOGM_EXCEPTION, "Exception {}", e);
        } catch (IOException e) {
            log.error(LOGM_EXCEPTION, "Exception {}", e);
        } catch (SQLException e) {
            log.error(LOGM_EXCEPTION, "Exception {}", e);
        }
        return false;
	}
	public static void main(String[] args) {

		String balanceFolder = configLoader.getDownloadToDir();
		if (!balanceFolder.endsWith("/")) {
			balanceFolder += "/";
		}
	    File balanceFilesPath = new File(balanceFolder + "accountBalances/balance");
        String balanceFilePath = "";
        String donePath = "";
        try {
        
            for (final File nodeFolders : balanceFilesPath.listFiles()) {
                donePath = nodeFolders.getCanonicalPath().toString().replace("/balance", "/processed");
                File targetPath = new File (donePath);
                targetPath.mkdirs();
                if (nodeFolders.isDirectory()) {
                    for (final File balanceFile : nodeFolders.listFiles()) {
                        if (processFile(balanceFile)) {
                            // move it
                            File destFile = new File(targetPath.getCanonicalPath() + File.separator + balanceFile.getName());

                            Files.move(balanceFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
                            log.info(MARKER, balanceFile.toPath() + " has been moved to " + destFile.getPath());
                            balanceFilePath = balanceFile.getCanonicalFile().toString();
                        }
                    }
                }
            } 
        } catch (IOException ex) {
            log.error(MARKER, "Fail to move {} to {} : {}",balanceFilePath, donePath, ex.getStackTrace());
        }
        log.info(MARKER, "Balance History processing done");
	}
}
