@startuml
title Stacked State for a contract call making an inner contract call

object "Frame2 : RWCachingStackFrame" as Frame2 {
   ap1 = <ref ap1>
   ap2 = //deleted//
   am = //no such account// (a.k.a. "missing")
   an = //updated// <value an> (new account)
}

object "Frame1 : RWCachingStackFrame" as Frame1 {
   ap1 = <ref ap1>
   ap2 = <ref ap2>
   am = //no such account//
}

object "Hedera state cache : ROCachingStackFrame" as ROCache {
   ap1 = <ref ap1>
   ap2 = <ref ap2>
   am = //no such account//
}
object "DatabaseBackedStackFrame" as  DBAccess {
   ap1 = present account <ap1>
   ap2 = present account <ap2>
}

Frame2 --> Frame1
Frame1 --> ROCache
ROCache --> DBAccess


note as Title
   state, for Frame2 after inner contract has
   read ""ap1"", ""ap2"", and ""am"", deleting ""ap2"", and
   creating new account ""an""
end note
Title --[hidden]>Frame2
note left of Frame2 #palegreen : top of\nframe stack
note left of Frame2 : inner contract call\n(called by ""Frame1"")
note left of Frame1 : outer contract call (the one\nfor ""eth_EstimateGas"")
note left of ROCache #palegreen: empty StateStack starts here with\na R/O cache over the database
note left of DBAccess : R/O access to the\ndatabase for entities
@enduml
