@startuml
title ""UpdatableReferenceCache"" State Diagram
caption "Given an account see which (of the 5) states it is in, start there.\n~"Not yet fetched~" is the state iff none of the other states apply."
hide empty description

state get <<choice>>
state del <<choice>>
state "invalid" as error #red
state "not yet\nfetched" as fetch

fetch --> get : get()
get --> present : retrieved\nvalue
get --> missing : retrieved\nvalue\ndoesn't\nexist

fetch --> updated : update()

fetch --> del : delete()
del --> deleted : retrieved\nvalue
del --> error : retrieved\nvalue\ndoesn't\nexist

'try to force present/missing/updated/deleted to be a square
present -right[#transparent]-> missing
present -down[#transparent]-> updated
updated -right[#transparent]-> deleted
missing -down[#transaprent]-> deleted

'try to force the delete choice to be on same level as get choice - almost works
get -right[#transparent]-> del
'try to force the error box to be to right of deleted box - doesn't work
deleted -right[#transparent]-> error

present --> present : get()
present --> updated : update()
present --> deleted : delete()

missing --> missing : get()
missing --> updated : update()
missing --> deleted : delete()

'try to force self-loop on updated to be on left side - but doesn't work
updated -left-> updated : get()
updated -left-> updated : update()
updated -right-> deleted : delete()

deleted --> deleted : get()
deleted -left-> updated : update()
deleted --> error : delete() a\ndeleted value
@enduml
