#!/bin/sh
set -e

rootDir=$(pwd)
filesStr="$(git diff --name-only --cached --diff-filter=ACMRTUB HEAD)"
#files=($filesStr)

#echo "Running Spotless to format ${#files[@]} changed files"
#./gradlew spotlessApply

#for file in ${files[@]}; do
  #git add "${rootDir}/${file}"
#done
