#!/bin/bash

# /*-
#  * ‌
#  * Hedera Mirror Node
#  * ​
#  * Copyright (C) 2019 Hedera Hashgraph, LLC
#  * ​
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *      http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
#  * ‍
#  */

set +x

# Jest executable location
jestExecutable='./node_modules/.bin/jest'

if [ "$TARGET" == "" ]; then
    echo -e "\n\n"
    echo -e "-----------------------------------------------------------------------------\n"
    echo -e "Error: You need to specify the target API server to run acceptance tests against.\n"
    echo -e "Please set TARGET variable to server:port\n";
    echo -e "Example: TARGET=11.22.33.44:5551 npm run acceptancetest\n\n";
    echo -e "-----------------------------------------------------------------------------\n\n"
else
    echo "Running acceptance tests against ${TARGET}"
    $jestExecutable --testPathPattern='__acceptancetests__/' $*;
fi

set -x
