{
 "title": "AlertManager",
 "tags": [
  "alertmanager",
  "alerts",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(severity!=\"\",namespace) "
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(alertmanager_build_info)"
   }
  ]
 },
 "panels": [
  {
   "title": "AlertManager Instances",
   "type": "stat",
   "description": "The number of AlertManager pods",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(alertmanager_build_info{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "description": "Current number of active alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(alertmanager_alerts{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Suppressed Alerts",
   "type": "stat",
   "description": "Current number of suppressed alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(alertmanager_alerts{state=\"suppressed\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Silenced Alerts",
   "type": "stat",
   "description": "Current number of silenced alerts.",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(alertmanager_silences{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "table",
   "description": "Alerts that are currently firing that are not specific to a namespace",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "namespace=~\"$namespace\",severity=~\"critical\"",
     "labelSelector": "alertname, summary, description, message,job,namespace",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "table",
   "description": "Alerts that are currently firing that are not specific to a namespace",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "namespace=~\"$namespace\",severity=~\"warning\"",
     "labelSelector": "alertname, summary, description, message,job,namespace",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Cluster Wide Alerts",
   "type": "table",
   "description": "Alerts that are currently firing that are not specific to a namespace",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "namespace=~\"\",severity=~\"critical|warning\"",
     "labelSelector": "alertname, summary, description, message,",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Notification Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(alertmanager_notifications_total{instance=~\"$instance\"}[5m])) by (integration) > 0",
     "legendFormat": "{{integration}}"
    }
   ]
  }
 ]
}