{
 "title": "Hedera / Mirror / REST API",
 "tags": [
  "api",
  "application",
  "hedera",
  "mirror",
  "rest"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "application", "query": "rest" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(nodejs_process_cpu_usage_percentage{container=\"$application\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(nodejs_process_cpu_usage_percentage{container=\"$application\",namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "stat",
   "description": "The rate of incoming requests",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_all_request_total{container=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))  "
    }
   ]
  },
  {
   "title": "Requests Processing",
   "type": "stat",
   "description": "The total number of all API requests currently in processing (no response yet)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(api_all_request_in_processing_total{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "stat",
   "description": "The average response size",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_response_size_bytes_sum{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code=~\"^2..\"}[$__rate_interval])) / \nsum(rate(api_response_size_bytes_count{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code=~\"^2..\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The total number of all API requests with server error response",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_all_errors_total{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) / \nsum(rate(api_all_request_total{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_request_duration_milliseconds_bucket{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",le=\"100\",code=~\"^2..$\"}[$__rate_interval])) +\nsum(rate(api_request_duration_milliseconds_bucket{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",le=\"250\",code=~\"^2..$\"}[$__rate_interval])))\n/ 2 / sum(rate(api_request_duration_milliseconds_count{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Node.js process CPU usage percentage",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nodejs_process_cpu_usage_percentage{container=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "description": "Average Node.js process used heap memory ",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nodejs_process_memory_heap_used_bytes{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Request Rate by Path",
   "type": "graph",
   "description": "The rate of all API requests received",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(api_request_total{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (path))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request Rate by Code",
   "type": "graph",
   "description": "The total number of all API requests with error response",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_request_total{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code=~\"^2..$\"}[$__rate_interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(api_request_total{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code=~\"^3..$\"}[$__rate_interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(api_request_total{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code=~\"^4..$\"}[$__rate_interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(api_request_total{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code=~\"^5..$\"}[$__rate_interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Duration by Path",
   "type": "graph",
   "description": "How long a request took to process and return a response",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(api_request_duration_milliseconds_sum{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) /  sum(rate(api_request_duration_milliseconds_count{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) > 0)",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum(rate(api_request_duration_milliseconds_sum{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (path) /  sum(rate(api_request_duration_milliseconds_count{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (path) > 0",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request Duration Distribution",
   "type": "bargauge",
   "description": "API request duration distributed into buckets",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_request_duration_milliseconds_bucket{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code=~\"^2..$\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "graph",
   "description": "API request size in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": " sum(api_request_size_bytes_sum{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}) / \n sum(api_request_size_bytes_count{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Error Rate by Code",
   "type": "graph",
   "description": "The total number of all API requests with error response",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_request_total{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code!~\"^2..$\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Response Size by Path",
   "type": "graph",
   "description": "API response size in bytes by path",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_response_size_bytes_sum{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code=~\"^2..\"}[$__rate_interval])) by (path) / \nsum(rate(api_response_size_bytes_count{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",code=~\"^2..\"}[$__rate_interval])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Response Size Distribution",
   "type": "bargauge",
   "description": "API response size distributed into buckets",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_response_size_bytes_bucket{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Node.js process memory",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_process_memory_external_bytes{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "External"
    },
    {
     "expr": "sum(nodejs_process_memory_rss_bytes{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(nodejs_process_memory_heap_used_bytes{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Heap used"
    },
    {
     "expr": "sum(nodejs_process_memory_heap_total_bytes{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Heap total"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "Node.js process CPU utilization",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_process_cpu_usage_percentage{container=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_component=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  }
 ]
}