{
 "title": "Hedera / Mirror / Importer",
 "tags": [
  "hedera",
  "mirror",
  "importer",
  "application"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "application", "query": "hedera-mirror-importer" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(system_cpu_count{application=\"$application\"}, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(system_cpu_count{application=\"$application\",namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "stat",
   "description": "The average number of overall transactions per second",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_transaction_latency_seconds_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HCS TPS",
   "type": "stat",
   "description": "The average number of consensus submit message transactions per second",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_transaction_latency_seconds_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",type=\"CONSENSUSSUBMITMESSAGE\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Transaction Size",
   "type": "stat",
   "description": "The average transaction size",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(hedera_mirror_transaction_size_bytes_sum{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}) / sum(hedera_mirror_transaction_size_bytes_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Record File Age",
   "type": "stat",
   "description": "How old the last processed record file is",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_parse_latency_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"RECORD\"}[$__rate_interval])) / sum(rate(hedera_mirror_parse_latency_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"RECORD\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Balance File Age",
   "type": "stat",
   "description": "How old the last processed balance file is",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_parse_latency_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=\"BALANCE\"}[$__rate_interval])) / sum(rate(hedera_mirror_parse_latency_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=\"BALANCE\"}[$__rate_interval]))"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Transaction Rate",
   "type": "graph",
   "description": "The transactions per second broken down by type",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_transaction_latency_seconds_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Transaction Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_transaction_size_bytes_sum{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type) / sum(rate(hedera_mirror_transaction_size_bytes_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Publish Duration",
   "type": "graph",
   "description": "The amount of time it took to publish the domain entity",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_importer_publish_duration_seconds_sum{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type) / sum(rate(hedera_mirror_importer_publish_duration_seconds_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(system_cpu_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(process_cpu_usage{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_states_threads{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (state)",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (pod, method, uri)",
     "legendFormat": "{{ method}} {{uri}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(process_files_max_files{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(process_files_open_files{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "open"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Database Rows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(db_table_size_rows{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (table)",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Database Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(postgres_rows_fetched_total{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "fetched"
    },
    {
     "expr": "sum(rate(postgres_rows_inserted_total{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "inserted"
    },
    {
     "expr": "sum(rate(postgres_rows_deleted_total{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(rate(postgres_rows_updated_total{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "updated"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(hikaricp_connections_idle{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(hikaricp_connections_max{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(hikaricp_connections_pending{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jdbc_connections_active{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(jdbc_connections_idle{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(jdbc_connections_max{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jdbc_connections_min{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Logs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(log4j2_events_total{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])) by (level)",
     "legendFormat": "{{ level }}"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "{pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "$stream Stream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "repeat": "stream",
   "collapsed": true,
   "panels": [
    {
     "title": "Stream List Rate",
     "type": "graph",
     "description": "The rate at which it the importer polls cloud storage for stream files",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short", "label": "Requests per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"list\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Stream Download Latency",
     "type": "graph",
     "description": "How long it took to search for new stream files from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status=~\"^2.*\"}[$__rate_interval])) by (action) / sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status=~\"^2.*\"}[$__rate_interval])) by (action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Download Stream Signature Rate",
     "type": "graph",
     "description": "The rate at which it the importer downloads stream file signatures from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "short", "label": "Request per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Stream Signature Latency",
     "type": "graph",
     "description": "How long it took to download the signature file from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Stream File Rate",
     "type": "graph",
     "description": "The rate at which it the importer downloads stream files from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "Request per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Stream File Latency",
     "type": "graph",
     "description": "How long it took to download stream files from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Stream File Size",
     "type": "graph",
     "description": "The average stream file size",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_response_bytes_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_response_bytes_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Signature File Size",
     "type": "graph",
     "description": "The average stream signature file size",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_response_bytes_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_response_bytes_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Stream List Size",
     "type": "graph",
     "description": "The average file size of the stream list response from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_response_bytes_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"list\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_response_bytes_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"list\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Signature Verification Rate",
     "type": "graph",
     "description": "The rate at which different node's signatures reach consensus",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_signature_verification_total{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status=\"CONSENSUS_REACHED\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Stream File Verification Rate",
     "type": "graph",
     "description": "The rate at which the stream file reaches consensus, hash chain verified (if applicable) and hash matches signature",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_stream_verification_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\"}[$__rate_interval])) by (success)",
       "legendFormat": "success={{success}}"
      }
     ]
    },
    {
     "title": "Stream File Verification Latency",
     "type": "graph",
     "description": "The duration in seconds it took to reach consensus,  verify hash chain (if applicable) and hash matches the signature.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_stream_verification_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=\"$stream\"}[$__rate_interval])) by (success) / sum(rate(hedera_mirror_download_stream_verification_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=\"$stream\"}[$__rate_interval])) by (success)",
       "legendFormat": "success={{success}}"
      }
     ]
    },
    {
     "title": "Cloud Storage Error Rate",
     "type": "graph",
     "description": "HTTP errors interacting with cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
     "yaxes": [
      { "format": "short", "label": "Errors per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status!~\"^2.*\"}[$__rate_interval])) by (status, action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Stream File Close Interval",
     "type": "graph",
     "description": "The difference between the consensus time of the last and first transaction in the stream file",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(hedera_mirror_stream_close_latency_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval]) / rate(hedera_mirror_stream_close_latency_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Stream Parse Duration",
     "type": "graph",
     "description": "The duration in seconds it took to parse the file and store it in the database",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_parse_duration_seconds_sum{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) by (success) / sum(rate(hedera_mirror_parse_duration_seconds_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",type=\"$stream\"}[$__rate_interval])) by (success)",
       "legendFormat": "success: {{success}}"
      }
     ]
    },
    {
     "title": "Consensus to Parsed Latency",
     "type": "graph",
     "description": "The difference in the consensus time of the last transaction in the file and the time at which the file was processed successfully",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_parse_latency_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) / sum(rate(hedera_mirror_parse_latency_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval]))",
       "legendFormat": "  "
      }
     ]
    }
   ]
  },
  {
   "title": "$stream Stream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stream List Rate",
     "type": "graph",
     "description": "The rate at which it the importer polls cloud storage for stream files",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short", "label": "Requests per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"list\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Stream Download Latency",
     "type": "graph",
     "description": "How long it took to search for new stream files from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status=~\"^2.*\"}[$__rate_interval])) by (action) / sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status=~\"^2.*\"}[$__rate_interval])) by (action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Download Stream Signature Rate",
     "type": "graph",
     "description": "The rate at which it the importer downloads stream file signatures from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "short", "label": "Request per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Stream Signature Latency",
     "type": "graph",
     "description": "How long it took to download the signature file from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Stream File Rate",
     "type": "graph",
     "description": "The rate at which it the importer downloads stream files from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "short", "label": "Request per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Stream File Latency",
     "type": "graph",
     "description": "How long it took to download stream files from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Stream File Size",
     "type": "graph",
     "description": "The average stream file size",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_response_bytes_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_response_bytes_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signed\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Download Signature File Size",
     "type": "graph",
     "description": "The average stream signature file size",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_response_bytes_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_response_bytes_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"signature\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Stream List Size",
     "type": "graph",
     "description": "The average file size of the stream list response from cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "yaxes": [
      { "format": "bytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_response_bytes_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"list\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount) / sum(rate(hedera_mirror_download_response_bytes_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", action=\"list\", status=~\"^2.*\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Signature Verification Rate",
     "type": "graph",
     "description": "The rate at which different node's signatures reach consensus",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_signature_verification_total{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status=\"CONSENSUS_REACHED\"}[$__rate_interval])) by (shard, realm, nodeAccount)",
       "legendFormat": "{{shard}}.{{realm}}.{{nodeAccount}}"
      }
     ]
    },
    {
     "title": "Stream File Verification Rate",
     "type": "graph",
     "description": "The rate at which the stream file reaches consensus, hash chain verified (if applicable) and hash matches signature",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_stream_verification_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\"}[$__rate_interval])) by (success)",
       "legendFormat": "success={{success}}"
      }
     ]
    },
    {
     "title": "Stream File Verification Latency",
     "type": "graph",
     "description": "The duration in seconds it took to reach consensus,  verify hash chain (if applicable) and hash matches the signature.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_stream_verification_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=\"$stream\"}[$__rate_interval])) by (success) / sum(rate(hedera_mirror_download_stream_verification_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=\"$stream\"}[$__rate_interval])) by (success)",
       "legendFormat": "success={{success}}"
      }
     ]
    },
    {
     "title": "Cloud Storage Error Rate",
     "type": "graph",
     "description": "HTTP errors interacting with cloud storage",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "yaxes": [
      { "format": "short", "label": "Errors per second" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_download_request_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\", type=~\"$stream\", status!~\"^2.*\"}[$__rate_interval])) by (status, action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Stream File Close Interval",
     "type": "graph",
     "description": "The difference between the consensus time of the last and first transaction in the stream file",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(hedera_mirror_stream_close_latency_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval]) / rate(hedera_mirror_stream_close_latency_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])",
       "legendFormat": "  "
      }
     ]
    },
    {
     "title": "Stream Parse Duration",
     "type": "graph",
     "description": "The duration in seconds it took to parse the file and store it in the database",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_parse_duration_seconds_sum{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) by (success) / sum(rate(hedera_mirror_parse_duration_seconds_count{application=\"$application\",namespace=~\"$namespace\",pod=~\"$pod\",type=\"$stream\"}[$__rate_interval])) by (success)",
       "legendFormat": "success: {{success}}"
      }
     ]
    },
    {
     "title": "Consensus to Parsed Latency",
     "type": "graph",
     "description": "The difference in the consensus time of the last transaction in the file and the time at which the file was processed successfully",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(hedera_mirror_parse_latency_seconds_sum{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval])) / sum(rate(hedera_mirror_parse_latency_seconds_count{application=\"$application\",namespace=~\"$namespace\", pod=~\"$pod\",type=~\"$stream\"}[$__rate_interval]))",
       "legendFormat": "  "
      }
     ]
    }
   ]
  }
 ]
}