{
 "title": "K6 eth_estimateGas performance testing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Http requests per 10 seconds /contracts/call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/api/v1/contracts/call\"}[10s])"
    }
   ]
  },
  {
   "title": "Max seconds for api contracts call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{uri=\"/api/v1/contracts/call\"}"
    }
   ]
  },
  {
   "title": "Average time per invocation of db query for the last 10 seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(spring_data_repository_invocations_seconds_sum[5m]) / rate(spring_data_repository_invocations_seconds_count[10s])"
    }
   ]
  },
  {
   "title": "Total number of db query invocations for the last 10 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "increase(spring_data_repository_invocations_seconds_count[10m])"
    }
   ]
  },
  {
   "title": "Http requests total for contracts/call",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/api/v1/contracts/call\"}"
    }
   ]
  },
  {
   "title": "Total gas per 10 seonds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(hedera_mirror_web3_call_gas_total[10s]))"
    }
   ]
  },
  {
   "title": "Gas per 10 seconds ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(hedera_mirror_web3_call_gas_total[10s])\n"
    }
   ]
  }
 ]
}