{
 "title": "ZFS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "loki", "label": "Loki", "query": "loki" },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(system_cpu_count,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_used_bytes{node=~\"$node\"},namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_zfs_arc_size,node)"
    }
   },
   { "name": "zfsDeviceId", "query": "sdb" }
  ]
 },
 "panels": [
  { "title": "PVC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZPool Ops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(node_zfs_zpool_dataset_reads{node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "reads/{{node}}/{{dataset}}"
    },
    {
     "expr": "irate(node_zfs_zpool_dataset_writes{node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "writes/{{node}}/{{dataset}}"
    }
   ]
  },
  {
   "title": "PVC Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{job=\"kubelet\", node=~\"$node\", namespace=~\"$namespace\"} / kubelet_volume_stats_capacity_bytes{job=\"kubelet\", node=~\"$node\", namespace=~\"$namespace\"}",
     "legendFormat": "{{node}}/{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{node=~\"$node\", namespace=~\"$namespace\"}",
     "legendFormat": "{{node}}/{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Waiting IO Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "irate(node_disk_io_now{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval])",
     "legendFormat": "read/{{node}}"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval])",
     "legendFormat": "write/{{node}}"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval])",
     "legendFormat": "read/{{node}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval])",
     "legendFormat": "write/{{node}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval])",
     "legendFormat": "reads/{{node}}"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{node=~\"$node\", device=\"$zfsDeviceId\"}[$__rate_interval])",
     "legendFormat": "write/{{node}}"
    }
   ]
  },
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Hits / Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "data-hits/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_hits{node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "metadata-hits/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_misses{node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "data-misses/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_demand_metadata_misses{node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "metadata-misses/{{node}}"
    }
   ]
  },
  {
   "title": "ARC HIT %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{node=~\"$node\"}[$__rate_interval]) / (irate(node_zfs_arc_demand_data_hits{node=~\"$node\"}[$__rate_interval]) + irate(node_zfs_arc_demand_data_misses{node=~\"$node\"}[$__rate_interval])) ",
     "legendFormat": "data/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_demand_data_hits{node=~\"$node\"}[$__rate_interval]) / (irate(node_zfs_arc_demand_data_hits{node=~\"$node\"}[$__rate_interval]) + irate(node_zfs_arc_demand_data_misses{node=~\"$node\"}[$__rate_interval])) ",
     "legendFormat": "metadata/{{node}}"
    }
   ]
  },
  {
   "title": "ARC BreakDown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_data_size{node=~\"$node\"}",
     "legendFormat": "data/{{node}}"
    },
    {
     "expr": "node_zfs_arc_metadata_size{node=~\"$node\"}",
     "legendFormat": "metadata/{{node}}"
    },
    {
     "expr": "node_zfs_arc_anon_size{node=~\"$node\"}",
     "legendFormat": "anon/{{node}}"
    },
    {
     "expr": "node_zfs_arc_hdr_size{node=~\"$node\"}",
     "legendFormat": "hdr/{{node}}"
    },
    {
     "expr": "node_zfs_arc_overhead_size{node=~\"$node\"}",
     "legendFormat": "overhead/{{node}}"
    }
   ]
  },
  {
   "title": "ARC Compress Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "node_zfs_arc_size{node=~\"$node\"} / node_zfs_arc_compressed_size{node=~\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "L2 ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_l2_asize{node=~\"$node\"}",
     "legendFormat": "asize/{{node}}"
    },
    {
     "expr": "node_zfs_arc_l2_hdr_size{node=~\"$node\"}",
     "legendFormat": "hdr/{{node}}"
    },
    {
     "expr": "node_zfs_arc_l2_size{node=~\"$node\"}",
     "legendFormat": "size/{{node}}"
    }
   ]
  },
  {
   "title": "Hit / Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "hits/{{node}}"
    },
    {
     "expr": "irate(node_zfs_arc_l2_misses{node=\"$node\"}[$__rate_interval])",
     "legendFormat": "misses/{{node}}"
    }
   ]
  },
  {
   "title": "Hit %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_zfs_arc_l2_hits{node=\"$node\"}[$__rate_interval]) / (irate(node_zfs_arc_l2_hits{node=\"$node\"}[$__rate_interval]) + irate(node_zfs_arc_l2_misses{node=\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Messages",
     "type": "logs",
     "description": "The log events",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{component=~\".*zfs.*\"}"
      }
     ]
    }
   ]
  }
 ]
}