# This container is only used for local development and automated testing
FROM citusdata/citus:12.0.0-alpine
RUN echo "max_locks_per_transaction = 1024" >> /usr/local/share/postgresql/postgresql.conf.sample

