-------------------
-- Create distributed tables for tables that can be distributed around an entity.
-- Colocate where possible with matching entity
-- Create reference tables for tables used only to describe with rare insert/updates
-------------------
